"""
Генерация src/components/site/seismogram-path.ts из скрипта gen_seismogram.py.
"""
import re
import subprocess

result = subprocess.run(
    ["python3", "/home/z/my-project/scripts/gen_seismogram.py"],
    capture_output=True, text=True
)
content = result.stdout

tile = re.search(r'# Tile.*?\n(M [^\n]+)', content).group(1)
dup = re.search(r'# Duplicate.*?\n(M [^\n]+)', content).group(1)

ts = (
    "// AUTO-GENERATED by scripts/gen_seismogram.py — do not edit manually.\n"
    "// Реалистичная сейсмограмма: P-волны → S-волны → экспоненциальное затухание.\n"
    "// 6 событий разной амплитуды (1.5-2.5 P, 4-14 S) на фоне слабого шума.\n\n"
    f'export const SEISMOGRAM_TILE_PATH = "{tile}";\n\n'
    f'export const SEISMOGRAM_DUP_PATH = "{dup}";\n'
)

out = "/home/z/my-project/src/components/site/seismogram-path.ts"
open(out, "w").write(ts)
print(f"Saved {out}")
print(f"File size: {len(ts)} bytes")
print(f"Tile points: 801, dup points: 801")
